name: Build for deployment
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@main
      with:
        node-version: 14
    - name: install dependencies
      run: npm install
    - name: Running Prettier Code Formatter
      run: npm run prettier:check
    - name: build
      run: npm run build --if-present